### ISSUE TITLE
Optimize the evaluation of querysets

### ISSUE THREAD

**Issue by mstajdohar** [genialis/django-rest-framework-reactive#4]
The evaluation of quesysets is slow. The biggest bottleneck is slow serialization. We should implement the following optimization, in order as proposed:

1. Support multiple query observer threads to be run in parallel as serialization is CPU-intensive. The initial design decision was to use greenlets, which yield during database queries (an I/O operation), while the most costly component in the current approach is data serialization (a CPU-intensive operation which does not yield and thus blocks all observers from running). This requires adding a mechanism to decide (consistently) which observers run in which threads so we can do proper request routing.

2. Heavily limit the fields that are returned in our viewsets (_e.g.,_ why are we returning almost 300k of data just to display a list of 20 data objects, each with just 5 fields: name, organism, source, contributor, date). The query should specify which fields to return and only those fields should be returned, e.g. by using query arguments (see example below). These field limits should then be reflected in database queries (less data to pull from the database) and in serialization of ORM models (less data to serialize). And then for lists, we don't need to pull full schemas and other data that is not needed to display a simple list.
  ```
  fields=name
  fields=descriptor.sample.organism   
  fields=descriptor.sample.source
  fields=contributor
  fields=created
  ```

3. Support non-reactive subscriptions.

**Comment by mstajdohar** [comment]
We have discussed the solution steps:

1.) Update resolwe-js not to subscribe to reactive changes by default.
2.) Support subscribing to changes in specific fields.

**Comment by kostko** [comment]
An additional solution is in #10, which introduces warnings for slow observers and automatic stopping for really slow observers (both is configurable).
