### ISSUE TITLE
Error migrating

### ISSUE THREAD

**Issue by BrianSidebotham** [genialis/django-rest-framework-reactive#65]
Using a blank Django project, installing django-rest-framework-reactive and migrating results in an error when migrating:

This is on a fresh install of Django 3.0.6

On a new project: `pip install djangorestframework-reactive` and then edit `settings.py` to add `rest_framework_reactive` - then `migrate` is broken.

Python version is `3.8`

```
(django-experiment) [brian@localhost]$ python ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, rest_framework_reactive, sessions
Running migrations:
  Applying rest_framework_reactive.0002_defer_order_constraint...Traceback (most recent call last):
  File "/home/brian/django-experiment/lib64/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/brian/django-experiment/lib64/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "DROP": syntax error
```

**Comment by gregorjerse** [comment]
From the description of your error I can see you are using SQLite as your DBMS. 

The only supported DBMS at the moment is PostgreSQL. Consider using PostgreSQL database in Docker. 

For example see `tests/docker-compose.yml` (define docker containers with PostgreSQL and Redis services) and `tests/settings.py ` (example of Django configuration that connects to PostgreSQL and Redis services inside docker containers).

**Comment by BrianSidebotham** [comment]
@gregorjerse Sorry for the slow response - that was exactly right. Sorry - I didn't see anywhere that noted only postgres :+1: Thanks.
